// NOMAAD Camp — shared site scripts
(function () {
  'use strict';

  var PLACEHOLDER = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 9'%3E%3Crect width='16' height='9' fill='%23EAE3D5'/%3E%3C/svg%3E";

  // Prefer WebP if the browser supports it and the file was generated by the build.
  var _webpSupported = false;
  (function () {
    var img = new Image();
    img.onload = function () { _webpSupported = (img.width > 0 && img.height > 0); };
    img.src = 'data:image/webp;base64,UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA';
  })();

  function toWebP(src) {
    if (!_webpSupported) return src;
    return src.replace(/\.(jpg|jpeg|png)(\?.*)?$/i, '.webp$2');
  }

  // ── HERO VIDEO: skip on mobile / slow connections ─────────────
  // Saves significant LCP time on phones — poster image is sufficient.
  (function () {
    var video = document.querySelector('.hero-video');
    if (!video) return;
    var isSmallScreen = window.matchMedia && window.matchMedia('(max-width: 760px)').matches;
    var saveData = navigator.connection && navigator.connection.saveData;
    var slowNet = navigator.connection && /^(slow-2g|2g|3g)$/.test(navigator.connection.effectiveType || '');
    if (isSmallScreen || saveData || slowNet) {
      video.removeAttribute('autoplay');
      video.preload = 'none';
      // Also remove inner <source> tags so the browser doesn't issue any video request.
      while (video.firstChild) video.removeChild(video.firstChild);
      try { video.pause(); } catch (e) {}
    }
  })();

  // ── CAMP CAROUSELS ───────────────────────────────────────────
  // Sets camp card thumbnails and populates carousel tracks from manifest.camps
  function initCampCarousels(camps) {
    if (!camps) return;
    var altText = { a: 'A кемп', b: 'B кемп', c: 'C кемп', mobile: 'Нүүдлийн кемп' };

    // Set thumbnail on each camp selector card using cover image from manifest
    document.querySelectorAll('[data-camp-thumb]').forEach(function (img) {
      var key = img.getAttribute('data-camp-thumb');
      var campData = camps[key];
      var cover = campData && campData.cover;
      if (!cover) return;
      img.setAttribute('data-src', cover);
      img.addEventListener('error', function () {
        img.src = PLACEHOLDER;
      }, { once: true });
    });

    // Populate each camp's carousel track (for [data-camp] elements)
    document.querySelectorAll('[data-camp]').forEach(function (root) {
      var key = root.getAttribute('data-camp');
      var campData = camps[key];
      var list = campData ? campData.gallery : [];
      var track = root.querySelector('.carousel-track');
      if (!track || !list || list.length === 0) return;

      track.innerHTML = '';
      list.forEach(function (src, i) {
        var img = document.createElement('img');
        img.className = 'carousel-slide defer-img';
        img.src = PLACEHOLDER;
        img.setAttribute('data-src', src);
        img.alt = (altText[key] || 'кемп') + ' - зураг ' + (i + 1);
        img.loading = 'lazy';
        img.decoding = 'async';
        img.addEventListener('error', function () {
          img.remove();
        }, { once: true });
        track.appendChild(img);
      });
    });
  }

  // ── CAMP DETAIL GALLERIES ────────────────────────────────────
  // Populates the horizontal scroll gallery shown when "Багц үзэх" is clicked.
  // Reads all images from manifest.camps[key].gallery — supports unlimited images.
  // Shows placeholder state if gallery is empty.
  function initCampDetailGalleries(camps) {
    if (!camps) return;
    var campAltText = { a: 'A кемп', b: 'B кемп', c: 'C кемп', mobile: 'Нүүдлийн кемп' };

    document.querySelectorAll('[data-camp-gallery]').forEach(function (gallery) {
      var key = gallery.getAttribute('data-camp-gallery');
      var campData = camps[key] || {};
      var images = campData.gallery || [];
      var track = gallery.querySelector('.camp-gallery__track');
      var emptyState = gallery.querySelector('.camp-gallery__empty');
      var viewport = gallery.querySelector('.camp-gallery__viewport');
      var featured = gallery.querySelector('.camp-gallery__featured');
      var featuredImg = gallery.querySelector('.camp-gallery__featured-img');
      if (!track) return;

      var setEmptyState = function (isEmpty) {
        track.style.display = isEmpty ? 'none' : '';
        if (featured) featured.hidden = isEmpty;
        if (viewport) viewport.classList.toggle('is-empty', isEmpty);
        if (emptyState) emptyState.hidden = !isEmpty;
      };

      var setFeaturedImage = function (thumb, immediate) {
        if (!featuredImg || !thumb) return;
        var newSrc = toWebP(thumb.getAttribute('data-src') || thumb.src);

        track.querySelectorAll('.camp-gallery__img').forEach(function (item) {
          item.classList.toggle('is-active', item === thumb);
        });

        if (immediate) {
          featuredImg.src = newSrc;
          featuredImg.setAttribute('data-src', newSrc);
          featuredImg.alt = thumb.alt || 'Кемпийн онцлох зураг';
          return;
        }

        featuredImg.style.opacity = '0';
        clearTimeout(featuredImg._fadeTimer);
        featuredImg._fadeTimer = setTimeout(function () {
          featuredImg.src = newSrc;
          featuredImg.setAttribute('data-src', newSrc);
          featuredImg.alt = thumb.alt || 'Кемпийн онцлох зураг';
          featuredImg.style.opacity = '';
        }, 480);
      };

      track.innerHTML = '';

      images.forEach(function (src, index) {
        var img = document.createElement('img');
        img.className = 'camp-gallery__img defer-img';
        img.src = PLACEHOLDER;
        img.setAttribute('data-src', src);
        img.alt = (campAltText[key] || 'Кемп') + ' - зураг ' + (index + 1);
        img.width = 160;
        img.height = 86;
        img.loading = 'lazy';
        img.decoding = 'async';
        img.tabIndex = 0;
        img.setAttribute('role', 'button');
        img.setAttribute('aria-label', 'Зураг сонгох');
        img.addEventListener('click', function () {
          setFeaturedImage(img, false);
        });
        img.addEventListener('keydown', function (event) {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            setFeaturedImage(img, false);
          }
        });
        img.addEventListener('error', function () {
          img.remove();
          if (track.children.length === 0) {
            setEmptyState(true);
          }
        }, { once: true });
        track.appendChild(img);

        if (index === 0 && featuredImg) {
          featuredImg.src = PLACEHOLDER;
          featuredImg.setAttribute('data-src', src);
          featuredImg.alt = 'Кемпийн онцлох зураг';
        }
      });

      if (track.children.length === 0) {
        setEmptyState(true);
        return;
      }

      setEmptyState(false);
      setFeaturedImage(track.querySelector('.camp-gallery__img'), true);
    });
  }

  // ── CATEGORY GALLERY ─────────────────────────────────────────
  // Renders the #gallery section from manifest.galleryCategories.
  // Tabs → featured image → thumbnail strip, all driven by manifest data.
  function initCategoryGallery(galleryCategories) {
    var container = document.getElementById('cat-gallery');
    if (!container) return;

    var categories = galleryCategories || {};
    var keys = Object.keys(categories);
    if (keys.length === 0) return;

    var tabsEl    = document.getElementById('cat-gallery-tabs');
    var featImg   = document.getElementById('cat-gallery-featured-img');
    var featWrap  = document.getElementById('cat-gallery-featured-wrap');
    var labelEl   = document.getElementById('cat-gallery-label');
    var descEl    = document.getElementById('cat-gallery-desc');
    var thumbsEl  = document.getElementById('cat-gallery-thumbs');
    if (!tabsEl || !featImg || !thumbsEl) return;
    featImg.loading = 'lazy';
    featImg.decoding = 'async';

    var activeKey   = null;
    var fadeTimer   = null;

    function setFeaturedSrc(src, alt) {
      if (fadeTimer) clearTimeout(fadeTimer);
      featImg.classList.add('is-fading');
      fadeTimer = setTimeout(function () {
        featImg.src = src ? toWebP(src) : '';
        featImg.alt = alt || '';
        featImg.classList.remove('is-fading');
      }, 480);
    }

    function setActiveThumb(activeIndex) {
      var thumbBtns = thumbsEl.querySelectorAll('.cat-gallery__thumb');
      thumbBtns.forEach(function (btn, i) {
        btn.classList.toggle('is-active', i === activeIndex);
        btn.setAttribute('aria-pressed', i === activeIndex ? 'true' : 'false');
      });
    }

    function activateCategory(key) {
      if (activeKey === key) return;
      activeKey = key;

      var cat    = categories[key] || {};
      var images = cat.images || [];

      tabsEl.querySelectorAll('.cat-gallery__tab').forEach(function (tab) {
        var isActive = tab.dataset.cat === key;
        tab.classList.toggle('is-active', isActive);
        tab.setAttribute('aria-pressed', isActive ? 'true' : 'false');
      });

      if (labelEl) labelEl.textContent = cat.label || key.toUpperCase();
      if (descEl)  descEl.textContent  = cat.description || '';

      thumbsEl.innerHTML = '';

      if (images.length === 0) {
        if (featWrap) featWrap.classList.add('cat-gallery__featured-wrap--empty');
        setFeaturedSrc('', '');
        return;
      }

      if (featWrap) featWrap.classList.remove('cat-gallery__featured-wrap--empty');
      setFeaturedSrc(images[0], cat.label || key);

      images.forEach(function (src, i) {
        var btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'cat-gallery__thumb' + (i === 0 ? ' is-active' : '');
        btn.setAttribute('aria-label', 'Зураг ' + (i + 1));
        btn.setAttribute('aria-pressed', i === 0 ? 'true' : 'false');

        var img = document.createElement('img');
        img.src = PLACEHOLDER;
        img.setAttribute('data-src', src);
        img.alt = (cat.title || cat.label || key) + ' - зураг ' + (i + 1);
        img.width = 88;
        img.height = 60;
        img.loading = 'lazy';
        img.decoding = 'async';
        img.className = 'defer-img';
        img.addEventListener('error', function () { btn.hidden = true; }, { once: true });

        btn.appendChild(img);
        btn.addEventListener('click', function () {
          setFeaturedSrc(src, cat.label || key);
          setActiveThumb(i);
        });
        thumbsEl.appendChild(btn);
      });

      if (window._nomaadDeferObserver) {
        thumbsEl.querySelectorAll('img.defer-img[data-src]').forEach(function (img) {
          window._nomaadDeferObserver.observe(img);
        });
      }
    }

    keys.forEach(function (key) {
      var cat = categories[key] || {};
      var tab = document.createElement('button');
      tab.type = 'button';
      tab.className = 'cat-gallery__tab';
      tab.dataset.cat = key;
      tab.setAttribute('aria-pressed', 'false');
      tab.textContent = cat.title || key;
      tab.addEventListener('click', function () { activateCategory(key); });
      tabsEl.appendChild(tab);
    });

    activateCategory(keys[0]);
  }

  // ── PARTNERS ────────────────────────────────────────────────
  // Renders partner logos from manifest.partners into #clients .trust-grid.
  function initPartners(partnerLogos) {
    var grid = document.querySelector('#clients .trust-grid');
    if (!grid) return;

    var logos = partnerLogos || [];
    if (logos.length === 0) return;

    grid.innerHTML = '';
    logos.forEach(function (src) {
      var figure = document.createElement('figure');
      figure.className = 'trust-item';

      var img = document.createElement('img');
      img.src = src;
      img.alt = src.split('/').pop().replace(/\.[^.]+$/, '').replace(/[-_]+/g, ' ') + ' лого';
      img.width = 120;
      img.height = 36;
      img.loading = 'lazy';
      img.decoding = 'async';

      figure.appendChild(img);
      grid.appendChild(figure);
    });
  }

  // ── INIT FROM MANIFEST ───────────────────────────────────────
  // Must run before deferred-img observer and carousel init
  var manifest = window.NOMAAD_IMAGES || {};
  initPartners(manifest.partners);
  initCampCarousels(manifest.camps);
  initCampDetailGalleries(manifest.camps);
  initCategoryGallery(manifest.galleryCategories);

  // ── MOBILE NAV TOGGLE ────────────────────────────────────────
  var nav = document.querySelector('.nav');
  var navToggle = document.querySelector('.nav-toggle');
  var navMenu = nav ? nav.querySelector('.nav-links') : null;
  if (nav && navToggle) {
    var setMenuOpen = function (isOpen) {
      nav.classList.toggle('is-open', isOpen);
      navToggle.setAttribute('aria-expanded', String(isOpen));
      document.body.classList.toggle('menu-open', isOpen);
    };

    navToggle.addEventListener('click', function () {
      setMenuOpen(!nav.classList.contains('is-open'));
    });
    document.addEventListener('click', function (e) {
      if (!nav.classList.contains('is-open')) return;
      if (!nav.contains(e.target)) setMenuOpen(false);
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && nav.classList.contains('is-open')) {
        setMenuOpen(false);
        navToggle.focus();
      }
    });
    document.querySelectorAll('.nav-links a').forEach(function (a) {
      a.addEventListener('click', function () { setMenuOpen(false); });
    });
    if (navMenu && !navMenu.id) navMenu.id = 'primary-nav';
  }

  // ── STICKY NAV ───────────────────────────────────────────────
  if (nav) {
    var onScroll = function () {
      nav.classList.toggle('is-scrolled', window.scrollY > 12);
    };
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
  }

  // ── ACTIVE NAV LINK ──────────────────────────────────────────
  var path = window.location.pathname.replace(/\/$/, '') || '/';
  document.querySelectorAll('.nav-links a').forEach(function (a) {
    var href = a.getAttribute('href');
    if (!href) return;
    var target = href.replace(/\/$/, '') || '/';
    if (target === path || (target === '/' && (path === '' || path === '/index.html'))) {
      a.classList.add('active');
    }
  });

  // ── SCROLL REVEAL ────────────────────────────────────────────
  if ('IntersectionObserver' in window) {
    var revealObs = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) {
          e.target.classList.add('is-visible');
          revealObs.unobserve(e.target);
        }
      });
    }, { threshold: 0.12 });
    document.querySelectorAll('.reveal').forEach(function (el) { revealObs.observe(el); });
  } else {
    document.querySelectorAll('.reveal').forEach(function (el) { el.classList.add('is-visible'); });
  }

  // ── DEFERRED IMAGE LOADING ───────────────────────────────────
  // Runs after manifest init so dynamically-created defer-img elements are included
  var deferredImages = document.querySelectorAll('img.defer-img[data-src]');
  var loadImage = function (img) {
    var src = img.getAttribute('data-src');
    if (!src) return;
    img.src = toWebP(src);
    img.removeAttribute('data-src');
  };
  if ('IntersectionObserver' in window) {
    var imgObs = new IntersectionObserver(function (entries, observer) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        loadImage(entry.target);
        observer.unobserve(entry.target);
      });
    }, { rootMargin: '220px 0px' });
    deferredImages.forEach(function (img) { imgObs.observe(img); });
    window._nomaadDeferObserver = imgObs;
  } else {
    deferredImages.forEach(loadImage);
  }

  // ── CAMP DETAIL TOGGLE ───────────────────────────────────────
  var campsSection = document.getElementById('camps');
  var campCards = campsSection ? campsSection.querySelectorAll('[data-camp-target]') : [];
  if (campCards.length > 0) {
    var campDetails = campsSection ? campsSection.querySelectorAll('.camp-detail') : [];
    var resetCampState = function () {
      campCards.forEach(function (card) {
        card.classList.remove('is-active');
        card.setAttribute('aria-expanded', 'false');
        var cta = card.querySelector('[data-camp-cta]');
        if (cta) cta.textContent = 'Багц үзэх →';
      });
      campDetails.forEach(function (detail) { detail.classList.remove('is-open'); });
    };
    var showCampDetail = function (targetId) {
      var targetDetail = null;
      campCards.forEach(function (card) {
        var isTarget = card.dataset.campTarget === targetId;
        card.classList.toggle('is-active', isTarget);
        card.setAttribute('aria-expanded', isTarget ? 'true' : 'false');
        var cta = card.querySelector('[data-camp-cta]');
        if (cta) cta.textContent = isTarget ? 'Хаах ↑' : 'Багц үзэх →';
      });
      campDetails.forEach(function (detail) {
        var isTarget = detail.id === targetId;
        detail.classList.toggle('is-open', isTarget);
        if (isTarget) targetDetail = detail;
      });
      if (targetDetail) {
        window.setTimeout(function () {
          targetDetail.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }, 120);
      }
    };
    campCards.forEach(function (card) {
      card.addEventListener('click', function () {
        if (card.classList.contains('is-active')) {
          resetCampState();
          return;
        }
        showCampDetail(card.dataset.campTarget);
      });
    });
    resetCampState();
  }

  // (Legacy Netlify-form contact handler removed — site now uses the quote modal
  // below which posts directly to n8n.)

  // ── QUOTE MODAL ──────────────────────────────────────────────
  var quoteModal   = document.getElementById('quote-modal');
  var quoteForm    = document.getElementById('quote-form');
  var quoteMessage = document.getElementById('quote-form-message');
  var quoteOpeners = document.querySelectorAll('[data-quote-open="true"]');

  var _modalFocusTrapHandler = null;
  var _modalOpenerEl = null;

  function _trapModalFocus(e) {
    var dialog = quoteModal.querySelector('[role="dialog"]');
    var focusable = dialog.querySelectorAll(
      'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
    );
    var first = focusable[0];
    var last  = focusable[focusable.length - 1];
    if (e.key !== 'Tab') return;
    if (e.shiftKey) {
      if (document.activeElement === first) { e.preventDefault(); last.focus(); }
    } else {
      if (document.activeElement === last)  { e.preventDefault(); first.focus(); }
    }
  }

  if (quoteModal && quoteForm && quoteOpeners.length > 0) {
    var closeTargets   = quoteModal.querySelectorAll('[data-quote-close]');
    var campSelect     = document.getElementById('field-camp');
    var tierSelect     = document.getElementById('field-tier');
    var orgInput       = document.getElementById('org-name');
    var contactInput   = document.getElementById('contact-name');
    var phoneInput     = document.getElementById('phone');
    var emailInput     = document.getElementById('email');
    var startInput     = document.getElementById('start-datetime');
    var endInput       = document.getElementById('end-datetime');
    var guestInput     = document.getElementById('guest-count');
    var locationWrap   = document.getElementById('location-field-wrap');
    var locationInput  = document.getElementById('location');
    var shuttleSelect  = document.getElementById('shuttle-service');
    var busCountInput  = document.getElementById('bus-count');
    var busCountWrap   = document.getElementById('bus-count-wrap');
    var contextHint    = document.getElementById('quote-context-hint');
    var estimateEl     = document.getElementById('quote-estimate');
    var modalTitleEl   = document.getElementById('quote-modal-title');

    var errOrg      = document.getElementById('err-org');
    var errContact  = document.getElementById('err-contact');
    var errPhone    = document.getElementById('err-phone');
    var errEmail    = document.getElementById('err-email');
    var errStart    = document.getElementById('err-start');
    var errEnd      = document.getElementById('err-end');
    var errGuests   = document.getElementById('err-guests');
    var errLocation = document.getElementById('err-location');

    // Capture original position of addons section for DOM removal/restore (C Кемп + Тусгай захиалга)
    var addonsSectionEl      = document.getElementById('quote-addons-section');
    var addonsSectionParent  = addonsSectionEl ? addonsSectionEl.parentNode : null;
    var addonsSectionNextSib = addonsSectionEl ? addonsSectionEl.nextSibling : null;

    // Capture original parent/index for every addon card so we can restore them after Production view
    var addonCardOriginals = [];
    quoteForm.querySelectorAll('.quote-addon-card').forEach(function (card) {
      var parent = card.parentNode;
      var index = Array.prototype.indexOf.call(parent.children, card);
      addonCardOriginals.push({ card: card, parent: parent, index: index });
    });

    // Stop click on quantity inputs from bubbling up to the card's checkbox toggle.
    // Replaces inline onclick="event.stopPropagation()" handlers (CSP-friendly).
    quoteForm.addEventListener('click', function (ev) {
      if (ev.target && ev.target.classList && ev.target.classList.contains('quote-addon-card__qty-input')) {
        ev.stopPropagation();
      }
    });

    // Card-now-div: clicking anywhere on the card body toggles the checkbox.
    // (Previously the parent <label> handled this, but we converted it to <div>
    // so number inputs and radios don't bubble up incorrectly.)
    quoteForm.querySelectorAll('.quote-addon-card').forEach(function (card) {
      card.addEventListener('click', function (ev) {
        var t = ev.target;
        if (!t) return;
        // Don't toggle when clicking interactive controls inside the card.
        if (t.matches('input, label, button, a, select, textarea')) return;
        if (t.closest('.quote-addon-card__quantity, .quote-addon-card__sub-options, .quote-addon-card__time-config')) return;
        var cb = card.querySelector('input[name="addons[]"]');
        if (!cb || cb.disabled) return;
        cb.checked = !cb.checked;
        cb.dispatchEvent(new Event('change', { bubbles: true }));
      });
    });

    function restoreAddonCardPositions() {
      var grouped = [];
      addonCardOriginals.forEach(function (entry) {
        var found = null;
        for (var i = 0; i < grouped.length; i++) {
          if (grouped[i].parent === entry.parent) { found = grouped[i]; break; }
        }
        if (!found) { found = { parent: entry.parent, entries: [] }; grouped.push(found); }
        found.entries.push(entry);
      });
      grouped.forEach(function (g) {
        g.entries.sort(function (a, b) { return a.index - b.index; });
        g.entries.forEach(function (entry) { g.parent.appendChild(entry.card); });
      });
    }

    function showFieldError(errEl, inputEl, msg) {
      if (!errEl) return;
      errEl.textContent = msg;
      errEl.hidden = false;
      if (inputEl) inputEl.classList.add('is-error');
    }

    function clearFieldError(errEl, inputEl) {
      if (!errEl) return;
      errEl.hidden = true;
      errEl.textContent = '';
      if (inputEl) inputEl.classList.remove('is-error');
    }

    function clearAllErrors() {
      clearFieldError(errOrg,      orgInput);
      clearFieldError(errContact,  contactInput);
      clearFieldError(errPhone,    phoneInput);
      clearFieldError(errEmail,    emailInput);
      clearFieldError(errStart,    startInput);
      clearFieldError(errEnd,      endInput);
      clearFieldError(errGuests,   guestInput);
      clearFieldError(errLocation, locationInput);
    }

    var CAMP_CAPACITY = {
      'NOMAAD Summit':  { min: 100,  max: 1000 },
      'NOMAAD Meadow':  { min: 50,   max: 300  },
      'NOMAAD Grove':   { min: 20,   max: 200  },
      'Нүүдлийн кемп':  { min: 10,   max: 1000 }
    };

    var DAY_PROGRAM_OPTIONS = ['Хагас өдрийн хөтөлбөр', 'Бүтэн өдрийн хөтөлбөр'];

    function getDayProgramLabel(campName) {
      return campName === 'Хагас өдрийн хөтөлбөр' ? 'Хагас өдрийн' : 'Бүтэн өдрийн';
    }

    function applyLocationVisibility(camp) {
      var isMobile = (camp || '').trim() === 'Нүүдлийн кемп';
      if (locationWrap) {
        if (isMobile) {
          locationWrap.style.display = 'flex';
          requestAnimationFrame(function () {
            requestAnimationFrame(function () {
              locationWrap.classList.add('is-visible');
            });
          });
        } else {
          locationWrap.classList.remove('is-visible');
          window.setTimeout(function () {
            if (!locationWrap.classList.contains('is-visible')) {
              locationWrap.style.display = 'none';
            }
          }, 280);
        }
        locationWrap.setAttribute('aria-hidden', String(!isMobile));
      }
      if (locationInput) {
        locationInput.required = isMobile;
        if (!isMobile) locationInput.value = '';
      }
    }

    function openQuoteModal(prefill) {
      _modalOpenerEl = document.activeElement;
      quoteModal.classList.add('is-open');
      quoteModal.setAttribute('aria-hidden', 'false');
      document.body.classList.add('modal-open');
      if (_modalFocusTrapHandler) document.removeEventListener('keydown', _modalFocusTrapHandler);
      _modalFocusTrapHandler = _trapModalFocus;
      document.addEventListener('keydown', _modalFocusTrapHandler);

      var quoteMode = (prefill && prefill.quoteMode) || 'camp';
      var camp    = (prefill && prefill.camp)    || '';
      var tier    = (prefill && prefill.tier)    || '';
      var feature = (prefill && prefill.feature) || '';
      var shuttle = (prefill && prefill.shuttle) || 'Сонгохгүй';

      var isDayProgram = (quoteMode === 'day-program');
      quoteModal.dataset.quoteMode = quoteMode;

      if (modalTitleEl) {
        if (isDayProgram) {
          modalTitleEl.textContent = 'Өдрийн хөтөлбөр · ' + getDayProgramLabel(camp) + ' багцын үнийн санал авах';
        } else {
          modalTitleEl.textContent = 'Үнийн санал авах';
        }
      }

      if (campSelect) campSelect.value = camp;
      if (tierSelect) tierSelect.value = tier;
      if (guestInput) {
        var cap = CAMP_CAPACITY[camp];
        guestInput.min = cap ? cap.min : 1;
        guestInput.max = cap ? cap.max : '';
      }

      if (contextHint) {
        if (isDayProgram) {
          contextHint.textContent = 'Та Өдрийн хөтөлбөр · ' + getDayProgramLabel(camp) + ' багцын үнийн санал авах гэж байна.';
          contextHint.hidden = false;
        } else if (camp && tier) {
          contextHint.textContent = 'Та ' + camp + ' · ' + tier + ' багцын үнийн санал авах гэж байна.';
          contextHint.hidden = false;
        } else {
          contextHint.hidden = true;
        }
      }

      if (shuttleSelect) shuttleSelect.value = shuttle;

      applyLocationVisibility(camp);
      clearAllErrors();
      if (quoteMessage) { quoteMessage.textContent = ''; quoteMessage.className = 'quote-form__message'; }

      // Apply tier inclusions and set qty defaults based on current guest count
      applyTierInclusions(tier);

      // C Кемп + Тусгай захиалга: remove add-ons from DOM entirely, show custom order message
      var isCCustomOrder = (camp === 'NOMAAD Grove' && tier === 'Тусгай захиалга');
      var customOrderMsg = document.getElementById('quote-custom-order-msg');
      if (customOrderMsg) customOrderMsg.hidden = !isCCustomOrder;
      var dayProgramMsg = document.getElementById('quote-day-program-msg');
      if (dayProgramMsg) dayProgramMsg.hidden = !isDayProgram;
      if (isCCustomOrder || isDayProgram) {
        if (addonsSectionEl && addonsSectionEl.parentNode) addonsSectionEl.parentNode.removeChild(addonsSectionEl);
      } else {
        if (addonsSectionEl && !addonsSectionEl.parentNode && addonsSectionParent) {
          addonsSectionParent.insertBefore(addonsSectionEl, addonsSectionNextSib);
        }
      }

      var currentGuests = guestInput ? (parseInt(guestInput.value, 10) || 0) : 0;
      quoteForm.querySelectorAll('.quote-addon-card__qty-input').forEach(function (qtyInput) {
        var card = qtyInput.closest('.quote-addon-card');
        var cb = card ? card.querySelector('input[name="addons[]"]') : null;
        if (cb && cb.disabled) return;
        if (currentGuests > 0) {
          qtyInput.value = currentGuests;
          qtyInput.max = currentGuests;
        }
      });
      updateAutoScaleLabels(currentGuests);
      updateEstimate();

      window.setTimeout(function () {
        if (orgInput) orgInput.focus();
      }, 20);
    }

    function closeQuoteModal() {
      quoteModal.classList.remove('is-open');
      quoteModal.setAttribute('aria-hidden', 'true');
      document.body.classList.remove('modal-open');
      if (_modalFocusTrapHandler) {
        document.removeEventListener('keydown', _modalFocusTrapHandler);
        _modalFocusTrapHandler = null;
      }
      if (_modalOpenerEl && _modalOpenerEl.focus) _modalOpenerEl.focus();
      _modalOpenerEl = null;
      if (contextHint) contextHint.hidden = true;
      if (estimateEl) { estimateEl.hidden = true; estimateEl.innerHTML = ''; }
      var nudgeElClose = document.getElementById('tier-nudge');
      if (nudgeElClose) nudgeElClose.hidden = true;
      var prodLinkElClose = document.getElementById('production-link');
      if (prodLinkElClose) prodLinkElClose.hidden = true;
      var tierSuccessElClose = document.getElementById('tier-success');
      if (tierSuccessElClose) { tierSuccessElClose.classList.remove('fade-out'); tierSuccessElClose.hidden = true; }
      if (campSelect) campSelect.value = '';
      if (tierSelect) tierSelect.value = '';
      if (guestInput) guestInput.value = '';
      if (shuttleSelect) shuttleSelect.value = 'Сонгохгүй';
      if (busCountInput) busCountInput.value = 1;
      if (busCountWrap)  busCountWrap.style.display = 'none';
      quoteModal.removeAttribute('data-quote-mode');
      if (modalTitleEl) modalTitleEl.textContent = 'Үнийн санал авах';
      applyLocationVisibility('');
      clearAllErrors();
      // Reset custom order message visibility and restore add-ons section to DOM if removed
      var customOrderMsgClose = document.getElementById('quote-custom-order-msg');
      if (customOrderMsgClose) customOrderMsgClose.hidden = true;
      var dayProgramMsgClose = document.getElementById('quote-day-program-msg');
      if (dayProgramMsgClose) dayProgramMsgClose.hidden = true;
      if (addonsSectionEl && !addonsSectionEl.parentNode && addonsSectionParent) {
        addonsSectionParent.insertBefore(addonsSectionEl, addonsSectionNextSib);
      }
      // Reset add-on UI — restore any cards moved to the Production included section
      restoreAddonCardPositions();
      var includedSection = document.getElementById('quote-addons-included-cards');
      var optionalLabel   = document.getElementById('quote-addons-optional-label');
      var titlePerPerson  = document.getElementById('quote-addons-title-per-person');
      var titleFlat       = document.getElementById('quote-addons-title-flat');
      var groupPerPerson  = document.getElementById('quote-addons-group-per-person');
      var groupFlat       = document.getElementById('quote-addons-group-flat');
      if (includedSection) includedSection.hidden = true;
      if (optionalLabel)   optionalLabel.hidden   = true;
      if (titlePerPerson)  titlePerPerson.hidden  = false;
      if (titleFlat)       titleFlat.hidden       = false;
      if (groupPerPerson)  groupPerPerson.hidden  = false;
      if (groupFlat)       groupFlat.hidden       = false;
      quoteForm.querySelectorAll('input[name="addons[]"]').forEach(function (cb) {
        cb.checked = false;
        cb.disabled = false;
      });
      quoteForm.querySelectorAll('.quote-addon-card').forEach(function (card) {
        card.classList.remove('quote-addon-card--included');
        var badge = card.querySelector('.quote-addon-card__included-badge');
        if (badge) badge.remove();
      });
      quoteForm.querySelectorAll('.quote-addon-card__time-config').forEach(function (el) { el.hidden = true; });
      quoteForm.querySelectorAll('.quote-addon-card__sub-options').forEach(function (el) { el.hidden = true; });
      quoteForm.querySelectorAll('.quote-addon-card__quantity').forEach(function (el) { el.hidden = true; });
      quoteForm.querySelectorAll('.quote-addon-card__qty-input').forEach(function (el) { el.disabled = false; });
      quoteForm.querySelectorAll('.quote-addon-card__qty-text').forEach(function (el) { el.hidden = false; });
      quoteForm.querySelectorAll('.quote-addon-card__qty-total').forEach(function (el) { el.textContent = '—'; });
      var bartenderPriceEl = document.querySelector('[data-bartender-price]');
      if (bartenderPriceEl) bartenderPriceEl.textContent = '+500,000₮ (1 bartender)';
      var djPriceEl = document.querySelector('[data-dj-price]');
      if (djPriceEl) djPriceEl.textContent = '+1,000,000₮';
      var medicalPriceEl = document.querySelector('[data-medical-price]');
      if (medicalPriceEl) medicalPriceEl.textContent = '+1,000,000₮';
      var securityPriceEl = document.querySelector('[data-security-price]');
      if (securityPriceEl) securityPriceEl.textContent = '+1,000,000₮';
    }

    // Clear inline errors on user input
    var clearOnChange = [
      [orgInput,      errOrg,      orgInput],
      [contactInput,  errContact,  contactInput],
      [phoneInput,    errPhone,    phoneInput],
      [emailInput,    errEmail,    emailInput],
      [startInput,    errStart,    startInput],
      [endInput,      errEnd,      endInput],
      [guestInput,    errGuests,   guestInput],
      [locationInput, errLocation, locationInput]
    ];
    clearOnChange.forEach(function (tuple) {
      var el = tuple[0]; var errEl = tuple[1]; var inputEl = tuple[2];
      if (!el) return;
      el.addEventListener('input',  function () { clearFieldError(errEl, inputEl); });
      el.addEventListener('change', function () { clearFieldError(errEl, inputEl); });
    });

    // ── PRICE ESTIMATE ─────────────────────────────────────────
    var PRICE_TABLE = {
      'Үндсэн': { 'NOMAAD Summit': 180000, 'NOMAAD Meadow': 180000, 'NOMAAD Grove': 180000, 'Нүүдлийн кемп': 180000 },
      'Стандарт': { 'NOMAAD Summit': 220000, 'NOMAAD Meadow': 220000, 'NOMAAD Grove': 220000, 'Нүүдлийн кемп': 220000 }
    };
    var DAY_PROGRAM_PRICE_TABLE = {
      'Хагас өдрийн хөтөлбөр': 100000,
      'Бүтэн өдрийн хөтөлбөр':  150000
    };
    var SHUTTLE_PRICE = {
      'Сонгохгүй': 0,
      'Өдрөөр / 2 талдаа — 1,000,000₮': 1000000,
      'Хоног / 2 талдаа — 1,200,000₮': 1200000
    };
    var SHUTTLE_LABEL = {
      'Өдрөөр / 2 талдаа — 1,000,000₮': 'Тээвэр (өдрөөр)',
      'Хоног / 2 талдаа — 1,200,000₮': 'Тээвэр (хоногоор)'
    };

    var TIER_INCLUSIONS = {
      'Үндсэн': [],
      'Стандарт': [
        'welcome_drink', 'sleeping_bag', 'coffee_corner',
        'lunch_upgrade', 'dinner_upgrade',
        'moonbeam_lounge', 'bartender_service'
      ],
      'Премиум': [
        'welcome_drink', 'sleeping_bag', 'coffee_corner',
        'lunch_upgrade', 'dinner_upgrade',
        'moonbeam_lounge', 'bartender_service',
        'amenity_kit', 'dj_service', 'photo_4h',
        'led_screen_18m2', 'late_snacks'
      ]
    };

    function getTierInclusions(campName, tier) {
      var included = TIER_INCLUSIONS[tier] ? TIER_INCLUSIONS[tier].slice() : [];
      if (tier === 'Премиум' && campName === 'NOMAAD Grove') {
        included = included.filter(function (item) { return item !== 'led_screen_18m2'; });
      }
      return included;
    }


    function formatMNT(n) {
      return n.toLocaleString('en-US') + '₮';
    }

    function calculateDJPrice() {
      var startEl = document.querySelector('[name="dj_start_time"]');
      var endEl   = document.querySelector('[name="dj_end_time"]');
      if (!startEl || !endEl) return 1000000;
      var duration = parseInt(endEl.value, 10) - parseInt(startEl.value, 10);
      if (duration <= 2) return 1000000;
      if (duration === 3) return 1500000;
      if (duration === 4) return 2000000;
      if (duration === 5) return 2500000;
      return 3000000;
    }

    function calculateBartenderPrice(guests) {
      var count = Math.ceil(guests / 75) || 1;
      return count * 500000;
    }

    function calculateMedicalPrice(guests) {
      return (Math.ceil(guests / 500) || 1) * 1000000;
    }

    function calculateSecurityPrice(guests) {
      return Math.max(2, Math.ceil(guests / 100)) * 500000;
    }

    function getProductionPricePerPerson() {
      return 280000;
    }

    function applyTierInclusions(tier) {
      var campName = campSelect ? campSelect.value : '';
      var includedItems = getTierInclusions(campName, tier);

      var includedSection  = document.getElementById('quote-addons-included-cards');
      var includedGrid     = document.getElementById('quote-addons-included-grid');
      var optionalLabel    = document.getElementById('quote-addons-optional-label');
      var groupPerPerson   = document.getElementById('quote-addons-group-per-person');
      var groupFlat        = document.getElementById('quote-addons-group-flat');
      var titlePerPerson   = document.getElementById('quote-addons-title-per-person');
      var titleFlat        = document.getElementById('quote-addons-title-flat');

      // For non-Production/non-Experience tiers, restore cards to original positions and hide included UI
      if (tier !== 'Премиум' && tier !== 'Стандарт') {
        restoreAddonCardPositions();
        if (includedSection) includedSection.hidden = true;
        if (optionalLabel)   optionalLabel.hidden   = true;
        if (titlePerPerson)  titlePerPerson.hidden  = false;
        if (titleFlat)       titleFlat.hidden       = false;
        if (groupPerPerson)  groupPerPerson.hidden  = false;
        if (groupFlat)       groupFlat.hidden       = false;
      }

      quoteForm.querySelectorAll('input[name="addons[]"]').forEach(function (cb) {
        var card = cb.closest('.quote-addon-card');
        if (!card) return;
        var isIncluded = includedItems.indexOf(cb.value) !== -1;
        if (isIncluded) {
          cb.checked = true;
          cb.disabled = true;
          card.classList.add('quote-addon-card--included');
          if (!card.querySelector('.quote-addon-card__included-badge')) {
            var badge = document.createElement('span');
            badge.className = 'quote-addon-card__included-badge';
            badge.textContent = tier + ' багцад багтсан';
            var nameEl = card.querySelector('.quote-addon-card__name');
            if (nameEl) nameEl.appendChild(badge);
          }
          // Move included cards into the included section grid
          if ((tier === 'Премиум' || tier === 'Стандарт') && includedGrid) {
            includedGrid.appendChild(card);
          }
          var qtyDiv = card.querySelector('.quote-addon-card__quantity');
          if (qtyDiv) {
            if (cb.dataset.type !== 'per-person') {
              qtyDiv.hidden = true;
            } else {
              // Per-person included items: show qty div with disabled auto-filled input
              qtyDiv.hidden = false;
              var qtyInputEl = qtyDiv.querySelector('.quote-addon-card__qty-input');
              var gNow = guestInput ? (parseInt(guestInput.value, 10) || 0) : 0;
              if (qtyInputEl) {
                qtyInputEl.disabled = true;
                if (gNow > 0) qtyInputEl.value = gNow;
              }
              if (tier === 'Премиум' || tier === 'Стандарт') {
                // Lock price display: replace unit-price text with included label
                var qtyTextEl = qtyDiv.querySelector('.quote-addon-card__qty-text');
                if (qtyTextEl) qtyTextEl.hidden = true;
                var totalEl = qtyDiv.querySelector('.quote-addon-card__qty-total');
                if (totalEl) totalEl.textContent = '· нэмэлт төлбөр авахгүй';
              } else {
                if (gNow > 0) {
                  updateQtyTotal(qtyDiv, parseInt(cb.dataset.price, 10), gNow);
                }
              }
            }
          }
          var subOpts = card.querySelector('.quote-addon-card__sub-options');
          if (subOpts) subOpts.hidden = true;
          var timeConf = card.querySelector('.quote-addon-card__time-config');
          if (timeConf) timeConf.hidden = true;
        } else {
          cb.disabled = false;
          card.classList.remove('quote-addon-card--included');
          var existingBadge = card.querySelector('.quote-addon-card__included-badge');
          if (existingBadge) existingBadge.remove();
          var existingQtyInput = card.querySelector('.quote-addon-card__qty-input');
          if (existingQtyInput) existingQtyInput.disabled = false;
        }
      });

      if (tier === 'Премиум' || tier === 'Стандарт') {
        var includedTitleEl = document.getElementById('quote-addons-included-title');
        if (includedTitleEl) includedTitleEl.textContent = tier + ' багцад багтсан үйлчилгээ';
        var productionList = document.querySelector('.quote-production-included-list');
        if (productionList) productionList.hidden = (tier !== 'Премиум');
        if (includedSection) includedSection.hidden = false;
        if (optionalLabel)   optionalLabel.hidden   = false;
        // Hide original group titles — the new section labels replace them
        if (titlePerPerson) titlePerPerson.hidden = true;
        if (titleFlat)      titleFlat.hidden      = true;
        // Hide flat group if all its cards were moved (nothing optional remains there)
        if (groupFlat) {
          var flatGrid = groupFlat.querySelector('.quote-addons__grid');
          groupFlat.hidden = !!(flatGrid && flatGrid.children.length === 0);
        }
      }
    }

    function updateAutoScaleLabels(guests) {
      var g = guests || 0;
      var bartenderCount = Math.ceil(g / 75) || 1;
      var bartenderPriceEl = document.querySelector('[data-bartender-price]');
      if (bartenderPriceEl) {
        if (g < 1) {
          bartenderPriceEl.textContent = '+500,000₮ (1 bartender)';
        } else {
          bartenderPriceEl.textContent = '+' + (bartenderCount * 500000).toLocaleString('en-US') + '₮ (' + bartenderCount + ' bartender, ' + g + ' хүний event-д)';
        }
      }
      var medicalCount = Math.ceil(g / 500) || 1;
      var medicalPriceEl = document.querySelector('[data-medical-price]');
      if (medicalPriceEl) {
        if (g < 1) {
          medicalPriceEl.textContent = '+1,000,000₮';
        } else {
          medicalPriceEl.textContent = '+' + (medicalCount * 1000000).toLocaleString('en-US') + '₮ (' + medicalCount + ' эмч, ' + g + ' хүний event-д)';
        }
      }
      var officerCount = Math.max(2, Math.ceil(g / 100));
      var securityPriceEl = document.querySelector('[data-security-price]');
      if (securityPriceEl) {
        if (g < 1) {
          securityPriceEl.textContent = '+1,000,000₮';
        } else {
          securityPriceEl.textContent = '+' + (officerCount * 500000).toLocaleString('en-US') + '₮ (' + officerCount + ' officer, ' + g + ' хүний event-д)';
        }
      }
    }

    function updateEstimate() {
      if (!estimateEl) return;
      var nudgeEl    = document.getElementById('tier-nudge');
      var prodLinkEl = document.getElementById('production-link');
      if (quoteModal.dataset.quoteMode === 'day-program') {
        var dpCamp   = campSelect  ? campSelect.value                : '';
        var dpGuests = guestInput  ? parseInt(guestInput.value, 10)  : 0;
        var dpShuttle = shuttleSelect ? shuttleSelect.value          : 'Сонгохгүй';

        if (!dpCamp || !dpGuests || dpGuests < 1) {
          estimateEl.hidden = true;
          estimateEl.innerHTML = '';
          if (nudgeEl)    nudgeEl.hidden    = true;
          if (prodLinkEl) prodLinkEl.hidden = true;
          return;
        }

        var dpPrice = DAY_PROGRAM_PRICE_TABLE[dpCamp];
        if (!dpPrice) {
          estimateEl.hidden = true;
          estimateEl.innerHTML = '';
          if (nudgeEl)    nudgeEl.hidden    = true;
          if (prodLinkEl) prodLinkEl.hidden = true;
          return;
        }

        var dpBase          = dpPrice * dpGuests;
        var dpBusCount      = busCountInput ? (parseInt(busCountInput.value, 10) || 1) : 1;
        var dpShuttleAmt    = (SHUTTLE_PRICE[dpShuttle] !== undefined ? SHUTTLE_PRICE[dpShuttle] : 0) * (dpShuttle !== 'Сонгохгүй' ? dpBusCount : 1);
        var dpShuttleLabel  = SHUTTLE_LABEL[dpShuttle];
        var dpTotal         = dpBase + dpShuttleAmt;
        var dpLabel         = getDayProgramLabel(dpCamp);

        var dpHtml = '<p class="quote-estimate__title">Урьдчилсан тооцоолол</p>';
        dpHtml += '<p class="quote-estimate__row">' + dpLabel + ' хөтөлбөр · ' + dpGuests + ' хүн</p>';
        dpHtml += '<p class="quote-estimate__row">' + dpGuests + ' × ' + formatMNT(dpPrice) + ' = <span class="quote-estimate__num">' + formatMNT(dpBase) + '</span></p>';
        dpHtml += '<p class="quote-estimate__row">Багцад багтсан үндсэн үйлчилгээ орсон.</p>';
        if (dpShuttleLabel) {
          dpHtml += '<p class="quote-estimate__row">' + dpShuttleLabel + ' (' + dpBusCount + ' автобус): <span class="quote-estimate__num">+' + formatMNT(dpShuttleAmt) + '</span></p>';
        }
        dpHtml += '<hr class="quote-estimate__divider">';
        dpHtml += '<p class="quote-estimate__total">~<span class="quote-estimate__num">' + formatMNT(dpTotal) + '</span>-с эхлэнэ</p>';
        dpHtml += '<p class="quote-estimate__disclaimer">Эцсийн үнэ нэмэлт үйлчилгээнээс хамааран өөрчлөгдөнө.</p>';

        estimateEl.innerHTML = dpHtml;
        estimateEl.hidden    = false;
        if (nudgeEl)    nudgeEl.hidden    = true;
        if (prodLinkEl) prodLinkEl.hidden = true;
        return;
      }
      var camp    = campSelect    ? campSelect.value               : '';
      var tier    = tierSelect    ? tierSelect.value               : '';
      var guests  = guestInput    ? parseInt(guestInput.value, 10) : 0;
      var shuttle = shuttleSelect ? shuttleSelect.value            : 'Сонгохгүй';

      if (!camp || !tier || !guests || guests < 1) {
        estimateEl.hidden = true;
        if (nudgeEl)    nudgeEl.hidden    = true;
        if (prodLinkEl) prodLinkEl.hidden = true;
        return;
      }

      // Strict guard: only C Кемп + Тусгай захиалга gets the custom-order treatment
      if (camp === 'NOMAAD Grove' && tier === 'Тусгай захиалга') {
        estimateEl.hidden = true;
        if (nudgeEl)    nudgeEl.hidden    = true;
        if (prodLinkEl) prodLinkEl.hidden = true;
        return;
      }

      estimateEl.hidden = false;

      var perPerson;
      if (tier === 'Премиум') {
        perPerson = getProductionPricePerPerson(guests, camp);
      } else {
        var campPrices = PRICE_TABLE[tier];
        if (!campPrices) {
          estimateEl.hidden = true;
          if (nudgeEl)    nudgeEl.hidden    = true;
          if (prodLinkEl) prodLinkEl.hidden = true;
          return;
        }
        perPerson = campPrices[camp];
        if (!perPerson) {
          estimateEl.hidden = true;
          if (nudgeEl)    nudgeEl.hidden    = true;
          if (prodLinkEl) prodLinkEl.hidden = true;
          return;
        }
      }

      var busCount = busCountInput ? (parseInt(busCountInput.value, 10) || 1) : 1;
      var base = perPerson * guests;
      var shuttleAmount = (SHUTTLE_PRICE[shuttle] !== undefined ? SHUTTLE_PRICE[shuttle] : 0) * (shuttle !== 'Сонгохгүй' ? busCount : 1);
      var shuttleLabelText = SHUTTLE_LABEL[shuttle];

      var perPersonAddonsSum = 0;
      var flatAddonsSum = 0;
      var addonRows = '';

      document.querySelectorAll('input[name="addons[]"]:checked').forEach(function (cb) {
        if (cb.disabled) { return; }
        var label = cb.dataset.label || cb.value;
        var type = cb.dataset.type;
        if (type === 'per-person') {
          var ppPrice = parseInt(cb.dataset.price, 10);
          var card = cb.closest('.quote-addon-card');
          var qtyInput = card ? card.querySelector('.quote-addon-card__qty-input') : null;
          var qty = qtyInput ? (parseInt(qtyInput.value, 10) || guests) : guests;
          var ppTotal = ppPrice * qty;
          perPersonAddonsSum += ppTotal;
          addonRows += '<p class="quote-estimate__row">' + label + ': ' + formatMNT(ppPrice) + ' × ' + qty + ' = <span class="quote-estimate__num">' + formatMNT(ppTotal) + '</span></p>';
        } else if (type === 'flat-dynamic' && cb.value === 'dj_service') {
          var djPrice = calculateDJPrice();
          flatAddonsSum += djPrice;
          addonRows += '<p class="quote-estimate__row">DJ service: <span class="quote-estimate__num">+' + formatMNT(djPrice) + '</span></p>';
        } else if (type === 'flat-auto' && cb.value === 'bartender_service') {
          var btPrice = calculateBartenderPrice(guests);
          var btCount = Math.ceil(guests / 75) || 1;
          flatAddonsSum += btPrice;
          addonRows += '<p class="quote-estimate__row">Bartender (' + btCount + '): <span class="quote-estimate__num">+' + formatMNT(btPrice) + '</span></p>';
        } else if (type === 'per-event-auto-medical') {
          var medPrice = calculateMedicalPrice(guests);
          var medCount = Math.ceil(guests / 500) || 1;
          flatAddonsSum += medPrice;
          addonRows += '<p class="quote-estimate__row">Эмнэлгийн тусламж (' + medCount + ' эмч): <span class="quote-estimate__num">+' + formatMNT(medPrice) + '</span></p>';
        } else if (type === 'per-event-auto-security') {
          var secPrice = calculateSecurityPrice(guests);
          var secCount = Math.max(2, Math.ceil(guests / 100));
          flatAddonsSum += secPrice;
          addonRows += '<p class="quote-estimate__row">Хамгаалалт (' + secCount + ' officer): <span class="quote-estimate__num">+' + formatMNT(secPrice) + '</span></p>';
        } else if (type === 'flat' && cb.dataset.price) {
          var flatPrice = parseInt(cb.dataset.price, 10);
          flatAddonsSum += flatPrice;
          addonRows += '<p class="quote-estimate__row">' + label + ': <span class="quote-estimate__num">+' + formatMNT(flatPrice) + '</span></p>';
        } else if (type === 'flat') {
          addonRows += '<p class="quote-estimate__row">' + label + ' (үнэ тохирно)</p>';
        }
      });

      var total = base + perPersonAddonsSum + flatAddonsSum + shuttleAmount;

      var html = '<p class="quote-estimate__title">Урьдчилсан тооцоолол</p>';
      if (tier === 'Премиум') {
        html += '<p class="quote-estimate__row">' + tier + ' багц · ' + guests + ' хүн · ' + formatMNT(perPerson) + '/хүн</p>';
      } else {
        html += '<p class="quote-estimate__row">' + tier + ' багц · ' + guests + ' хүн</p>';
      }
      html += '<p class="quote-estimate__row">' + guests + ' × ' + formatMNT(perPerson) + ' = <span class="quote-estimate__num">' + formatMNT(base) + '</span></p>';
      html += '<p class="quote-estimate__row">Багцад багтсан үндсэн үйлчилгээ орсон.</p>';
      if (addonRows) {
        html += '<p class="quote-estimate__row quote-estimate__row--addon-section">Нэмэлт үйлчилгээ:</p>';
        html += addonRows;
      } else {
        html += '<p class="quote-estimate__row">Нэмэлт үйлчилгээ: Сонгоогүй</p>';
      }
      if (shuttleLabelText) {
        html += '<p class="quote-estimate__row">' + shuttleLabelText + ' (' + busCount + ' автобус): <span class="quote-estimate__num">+' + formatMNT(shuttleAmount) + '</span></p>';
      }
      html += '<hr class="quote-estimate__divider">';
      html += '<p class="quote-estimate__total">~<span class="quote-estimate__num">' + formatMNT(total) + '</span>-с эхлэнэ</p>';
      html += '<p class="quote-estimate__disclaimer">Эцсийн үнэ байршил, нэмэлт үйлчилгээнээс хамааран өөрчлөгдөнө.</p>';
      estimateEl.innerHTML = html;

      checkTierUpgradeNudge();
    }

    function calculateAddonPrice(cb, guests) {
      var type = cb.dataset.type;
      if (type === 'per-person') {
        var ppPrice = parseInt(cb.dataset.price, 10);
        var card = cb.closest('.quote-addon-card');
        var qtyInput = card ? card.querySelector('.quote-addon-card__qty-input') : null;
        var qty = qtyInput ? (parseInt(qtyInput.value, 10) || guests) : guests;
        return ppPrice * qty;
      } else if (type === 'flat-dynamic' && cb.value === 'dj_service') {
        return calculateDJPrice();
      } else if (type === 'flat-auto' && cb.value === 'bartender_service') {
        return calculateBartenderPrice(guests);
      } else if (type === 'per-event-auto-medical') {
        return calculateMedicalPrice(guests);
      } else if (type === 'per-event-auto-security') {
        return calculateSecurityPrice(guests);
      } else if (type === 'flat' && cb.dataset.price) {
        return parseInt(cb.dataset.price, 10);
      }
      return 0;
    }

    function calculateAddonSum(guests, excludedCodes) {
      var sum = 0;
      quoteForm.querySelectorAll('input[name="addons[]"]:checked').forEach(function (cb) {
        if (cb.disabled) return;
        if (excludedCodes && excludedCodes.indexOf(cb.value) !== -1) return;
        sum += calculateAddonPrice(cb, guests);
      });
      return sum;
    }

    function calculateCurrentTotal() {
      var c    = campSelect    ? campSelect.value               : '';
      var t    = tierSelect    ? tierSelect.value               : '';
      var g    = guestInput    ? (parseInt(guestInput.value, 10) || 0) : 0;
      var sh   = shuttleSelect ? shuttleSelect.value            : 'Сонгохгүй';
      var bc   = busCountInput ? (parseInt(busCountInput.value, 10) || 1) : 1;
      if (!c || !t || g < 1) return 0;
      var perPerson;
      if (t === 'Премиум') {
        perPerson = getProductionPricePerPerson(g, c);
      } else {
        var cp = PRICE_TABLE[t];
        if (!cp || !cp[c]) return 0;
        perPerson = cp[c];
      }
      var shuttleAmt = (SHUTTLE_PRICE[sh] !== undefined ? SHUTTLE_PRICE[sh] : 0) * (sh !== 'Сонгохгүй' ? bc : 1);
      return perPerson * g + shuttleAmt + calculateAddonSum(g, null);
    }

    function calculateProductionTotal(campName, guests) {
      var sh = shuttleSelect ? shuttleSelect.value : 'Сонгохгүй';
      var bc = busCountInput ? (parseInt(busCountInput.value, 10) || 1) : 1;
      var shuttleAmt = (SHUTTLE_PRICE[sh] !== undefined ? SHUTTLE_PRICE[sh] : 0) * (sh !== 'Сонгохгүй' ? bc : 1);
      var base = getProductionPricePerPerson(guests, campName) * guests;
      var inclusions = getTierInclusions(campName, 'Премиум');
      return base + shuttleAmt + calculateAddonSum(guests, inclusions);
    }

    function calculateExperienceTotal(campName, guests) {
      var sh = shuttleSelect ? shuttleSelect.value : 'Сонгохгүй';
      var bc = busCountInput ? (parseInt(busCountInput.value, 10) || 1) : 1;
      var shuttleAmt = (SHUTTLE_PRICE[sh] !== undefined ? SHUTTLE_PRICE[sh] : 0) * (sh !== 'Сонгохгүй' ? bc : 1);
      var cp = PRICE_TABLE['Стандарт'];
      if (!cp || !cp[campName]) return Infinity;
      var base = cp[campName] * guests;
      var inclusions = getTierInclusions(campName, 'Стандарт');
      return base + shuttleAmt + calculateAddonSum(guests, inclusions);
    }

    function calculateEssentialEquivalentTotal(campName, guests) {
      var cp = PRICE_TABLE['Үндсэн'];
      if (!cp || !cp[campName]) return Infinity;
      var basePrice = cp[campName] * guests;
      var experienceInclusions = TIER_INCLUSIONS['Стандарт'];
      var inclusionsTotal = 0;
      experienceInclusions.forEach(function (code) {
        var cb = quoteForm.querySelector('input[name="addons[]"][value="' + code + '"]');
        if (!cb) return;
        var type = cb.dataset.type;
        if (type === 'per-person') {
          inclusionsTotal += parseInt(cb.dataset.price, 10) * guests;
        } else if (type === 'flat') {
          inclusionsTotal += parseInt(cb.dataset.price, 10);
        } else if (type === 'flat-auto') {
          inclusionsTotal += calculateBartenderPrice(guests);
        }
      });
      return basePrice + inclusionsTotal;
    }

    function getSelectedAddonCodes() {
      var codes = [];
      quoteForm.querySelectorAll('input[name="addons[]"]:checked').forEach(function (cb) {
        if (!cb.disabled) codes.push(cb.value);
      });
      return codes;
    }

    function getSelectedItemsInTier(tier, campName) {
      var tierItems = getTierInclusions(campName, tier);
      var result = [];
      quoteForm.querySelectorAll('input[name="addons[]"]:checked').forEach(function (cb) {
        if (tierItems.indexOf(cb.value) !== -1) result.push(cb.value);
      });
      return result;
    }

    function checkTierUpgradeNudge() {
      var guests = guestInput ? (parseInt(guestInput.value, 10) || 0) : 0;
      var currentTier = tierSelect ? tierSelect.value : '';
      var campName = campSelect ? campSelect.value : '';
      var nudge = document.getElementById('tier-nudge');
      var productionLink = document.getElementById('production-link');
      if (!nudge || !currentTier || !campName || guests < 1) {
        if (nudge) nudge.hidden = true;
        if (productionLink) productionLink.hidden = true;
        return;
      }

      if (currentTier === 'Премиум') {
        nudge.hidden = true;
        if (productionLink) productionLink.hidden = true;
        return;
      }

      if (currentTier === 'Үндсэн') {
        var currentTotal = calculateCurrentTotal();
        if (currentTotal > 0) {
          var userSelectedExperienceItems = getSelectedItemsInTier('Стандарт', campName);
          if (userSelectedExperienceItems.length >= 3) {
            var experienceTotal = calculateExperienceTotal(campName, guests);
            if (experienceTotal < currentTotal) {
              showUpgradeNudge(currentTotal - experienceTotal);
              if (productionLink) productionLink.hidden = false;
              return;
            }
          }
        }
      } else if (currentTier === 'Стандарт') {
        var essentialEquivalentTotal = calculateEssentialEquivalentTotal(campName, guests);
        var expTotal = calculateExperienceTotal(campName, guests);
        var savings = essentialEquivalentTotal - expTotal;
        if (savings > 0) {
          showSavingsConfirmation(savings);
          if (productionLink) productionLink.hidden = false;
          return;
        }
      }

      nudge.hidden = true;
      if (productionLink) productionLink.hidden = false;
    }

    function updateModalHeader(campName, tier) {
      if (contextHint && campName) {
        contextHint.textContent = 'Та ' + campName + ' · ' + tier + ' багцын үнийн санал авах гэж байна.';
        contextHint.hidden = false;
      }
    }

    function handleTierSwitch() {
      var currentGuests = guestInput ? (parseInt(guestInput.value, 10) || 0) : 0;
      var campName = campSelect ? campSelect.value : '';
      var savingsBeforeSwitch = calculateCurrentTotal() - calculateExperienceTotal(campName, currentGuests);
      if (tierSelect) tierSelect.value = 'Стандарт';
      applyTierInclusions('Стандарт');
      updateModalHeader(campName, 'Стандарт');
      quoteForm.querySelectorAll('.quote-addon-card__qty-input').forEach(function (qi) {
        var card = qi.closest('.quote-addon-card');
        var cb = card ? card.querySelector('input[name="addons[]"]') : null;
        if (cb && cb.disabled) return;
        if (currentGuests > 0) { qi.value = currentGuests; qi.max = currentGuests; }
      });
      updateAutoScaleLabels(currentGuests);
      updateEstimate();
      if (savingsBeforeSwitch > 0) showTierSuccessBanner(savingsBeforeSwitch);
    }

    function showUpgradeNudge(savings) {
      var nudge = document.getElementById('tier-nudge');
      if (!nudge) return;
      nudge.innerHTML = [
        '<div class="quote-tier-nudge__icon">💡</div>',
        '<div class="quote-tier-nudge__body">',
        '  <h4 class="quote-tier-nudge__title">Стандарт багц руу шилжвэл хэмнэлттэй</h4>',
        '  <div class="quote-tier-nudge__savings">',
        '    ✓ <strong>' + savings.toLocaleString() + '₮</strong> хэмнэнэ',
        '  </div>',
        '  <button type="button" class="btn btn--accent quote-tier-nudge__cta" data-tier-switch>',
        '    Стандарт багц руу шилжих →',
        '  </button>',
        '</div>'
      ].join('');
      nudge.classList.remove('quote-tier-nudge--success');
      nudge.hidden = false;
      var switchBtn = nudge.querySelector('[data-tier-switch]');
      if (switchBtn) switchBtn.addEventListener('click', handleTierSwitch);
    }

    function showSavingsConfirmation(savings) {
      var nudge = document.getElementById('tier-nudge');
      if (!nudge) return;
      nudge.innerHTML = [
        '<div class="quote-tier-nudge__icon">✓</div>',
        '<div class="quote-tier-nudge__body">',
        '  <h4 class="quote-tier-nudge__title">',
        '    Та Experience tier сонгож <strong>' + savings.toLocaleString() + '₮</strong> хэмнэлээ',
        '  </h4>',
        '</div>'
      ].join('');
      nudge.classList.add('quote-tier-nudge--success');
      nudge.hidden = false;
    }

    function showTierSuccessBanner(savings) {
      var banner = document.getElementById('tier-success');
      if (!banner) return;
      var savedEl = banner.querySelector('[data-saved-amount]');
      if (savedEl) savedEl.textContent = savings.toLocaleString() + '₮';
      banner.hidden = false;
      banner.classList.remove('fade-out');
      setTimeout(function () {
        banner.classList.add('fade-out');
        setTimeout(function () { banner.hidden = true; }, 300);
      }, 3000);
    }

    if (guestInput)    guestInput.addEventListener('input',   updateEstimate);
    if (shuttleSelect) shuttleSelect.addEventListener('change', function () {
      if (busCountWrap) {
        var selected = shuttleSelect.value !== 'Сонгохгүй';
        busCountWrap.style.display = selected ? '' : 'none';
        if (!selected && busCountInput) busCountInput.value = 1;
      }
      updateEstimate();
    });
    if (busCountInput) busCountInput.addEventListener('input', updateEstimate);

    // ── ADD-ON LISTENERS ───────────────────────────────────────
    document.querySelectorAll('input[name="addons[]"]').forEach(function (cb) {
      cb.addEventListener('change', function (e) {
        if (cb.disabled) return;
        var card = cb.closest('.quote-addon-card');
        // Per-person: toggle quantity input
        if (cb.dataset.type === 'per-person' && card) {
          var qtyDiv = card.querySelector('.quote-addon-card__quantity');
          if (qtyDiv) {
            qtyDiv.hidden = !e.target.checked;
            if (e.target.checked) {
              var qtyInput = qtyDiv.querySelector('.quote-addon-card__qty-input');
              var currentGuests = guestInput ? (parseInt(guestInput.value, 10) || 1) : 1;
              if (qtyInput) {
                qtyInput.value = currentGuests;
                qtyInput.max = currentGuests;
                updateQtyTotal(qtyDiv, parseInt(cb.dataset.price, 10), currentGuests);
              }
            }
          }
          // Welcome drink: also toggle sub-options
          var subOptions = card.querySelector('.quote-addon-card__sub-options');
          if (subOptions) subOptions.hidden = !e.target.checked;
        }
        // DJ: toggle time config
        if (cb.value === 'dj_service' && card) {
          var timeConfig = card.querySelector('.quote-addon-card__time-config');
          if (timeConfig) timeConfig.hidden = !e.target.checked;
        }
        updateEstimate();
      });
    });

    function updateQtyTotal(qtyDiv, unitPrice, qty) {
      var totalEl = qtyDiv.querySelector('.quote-addon-card__qty-total');
      if (totalEl && unitPrice && qty) {
        totalEl.textContent = formatMNT(unitPrice * qty);
      }
    }

    // Per-person quantity inputs: update total display and estimate
    document.querySelectorAll('.quote-addon-card__qty-input').forEach(function (qtyInput) {
      qtyInput.addEventListener('input', function () {
        var card = qtyInput.closest('.quote-addon-card');
        var cb = card ? card.querySelector('input[name="addons[]"]') : null;
        var unitPrice = cb ? parseInt(cb.dataset.price, 10) : 0;
        var qty = parseInt(qtyInput.value, 10) || 0;
        var qtyDiv = qtyInput.closest('.quote-addon-card__quantity');
        if (qtyDiv) updateQtyTotal(qtyDiv, unitPrice, qty);
        updateEstimate();
      });
    });

    var djStartSel = document.querySelector('[name="dj_start_time"]');
    var djEndSel   = document.querySelector('[name="dj_end_time"]');
    if (djStartSel) djStartSel.addEventListener('change', function () {
      updateEstimate();
      var priceEl = document.querySelector('[data-dj-price]');
      if (priceEl) priceEl.textContent = '+' + calculateDJPrice().toLocaleString('en-US') + '₮';
    });
    if (djEndSel) djEndSel.addEventListener('change', function () {
      updateEstimate();
      var priceEl = document.querySelector('[data-dj-price]');
      if (priceEl) priceEl.textContent = '+' + calculateDJPrice().toLocaleString('en-US') + '₮';
    });

    if (guestInput) {
      guestInput.addEventListener('input', function () {
        var g = parseInt(guestInput.value, 10) || 0;
        // Update all per-person qty inputs
        quoteForm.querySelectorAll('.quote-addon-card__qty-input').forEach(function (qtyInput) {
          var card = qtyInput.closest('.quote-addon-card');
          var cb = card ? card.querySelector('input[name="addons[]"]') : null;
          var qtyDiv = qtyInput.closest('.quote-addon-card__quantity');
          if (qtyDiv && qtyDiv.hidden) return;
          var unitPrice = cb ? parseInt(cb.dataset.price, 10) : 0;
          if (cb && cb.disabled) {
            // Included per-person items: always track guest count
            qtyInput.value = g;
            var currentTier = tierSelect ? tierSelect.value : '';
            if (currentTier !== 'Премиум' && currentTier !== 'Стандарт') {
              if (qtyDiv) updateQtyTotal(qtyDiv, unitPrice, g);
            }
            // For Production/Experience included items the total stays as "нэмэлт төлбөр авахгүй"
          } else {
            qtyInput.max = g;
            var currentVal = parseInt(qtyInput.value, 10) || 0;
            if (currentVal > g) {
              qtyInput.value = g;
              if (qtyDiv) updateQtyTotal(qtyDiv, unitPrice, g);
            }
          }
        });
        updateAutoScaleLabels(g);
        updateEstimate();
      });
    }
    // ── /ADD-ON LISTENERS ──────────────────────────────────────

    // Open modal from any quote trigger button
    quoteOpeners.forEach(function (link) {
      link.addEventListener('click', function (e) {
        e.preventDefault();
        var quoteMode   = (link.dataset.quoteMode   || 'camp').trim();
        var campName    = (link.dataset.campName    || '').trim();
        var tier        = (link.dataset.tier        || '').trim();
        var visualGroup = (link.dataset.visualGroup || '').trim();
        var feature     = '';
        if (visualGroup) {
          var checked = document.querySelector('input[name="' + visualGroup + '"]:checked');
          feature = checked ? checked.value : '';
        }
        openQuoteModal({ quoteMode: quoteMode, camp: campName, tier: tier, feature: feature, shuttle: 'Сонгохгүй' });
      });
    });

    closeTargets.forEach(function (el) {
      el.addEventListener('click', function () { closeQuoteModal(); });
    });

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && quoteModal.classList.contains('is-open')) {
        closeQuoteModal();
      }
    });

    var N8N_WEBHOOK_URL = 'https://chimun.app.n8n.cloud/webhook/59124f59-5317-4fff-8632-28e14b36ff72';

    quoteForm.addEventListener('submit', async function (e) {
      e.preventDefault();

      clearAllErrors();
      if (quoteMessage) { quoteMessage.textContent = ''; quoteMessage.className = 'quote-form__message'; }

      var fd       = new FormData(quoteForm);

      if ((fd.get('website') || '').trim()) return;

      var camp     = (fd.get('camp_name')      || '').trim();
      var tier     = (fd.get('package_tier')   || '').trim();
      var org      = (fd.get('organization')   || '').trim();
      var contact  = (fd.get('contact_name')   || '').trim();
      var phone    = (fd.get('phone')          || '').trim();
      var email    = (fd.get('email')          || '').trim();
      var startDt  = (fd.get('start_datetime') || '').trim();
      var endDt    = (fd.get('end_datetime')   || '').trim();
      var guests   = (fd.get('guest_count')    || '').trim();
      var location = (fd.get('location')       || '').trim();
      var isMobile = camp === 'Нүүдлийн кемп';

      var hasError = false;
      var firstErrorEl = null;

      function markError(errEl, inputEl, msg) {
        showFieldError(errEl, inputEl, msg);
        hasError = true;
        if (!firstErrorEl) firstErrorEl = inputEl;
      }

      if (!org)     markError(errOrg,     orgInput,      'Байгууллагын нэр оруулна уу.');
      if (!contact) markError(errContact, contactInput,  'Холбоо барих хүний нэр оруулна уу.');

      if (!phone) {
        markError(errPhone, phoneInput, 'Утасны дугаар оруулна уу.');
      } else {
        // Mongolian phone: 8 digits, optionally prefixed with +976 or 976
        var cleanPhone = phone.replace(/[\s\-\(\)\+]/g, '').replace(/^976/, '');
        if (!/^\d{7,8}$/.test(cleanPhone)) {
          markError(errPhone, phoneInput, 'Монгол утасны дугаар буруу байна. (жишээ: 99179417)');
        }
      }

      if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        markError(errEmail, emailInput, 'Имэйл хаяг буруу байна.');
      }

      if (!startDt) {
        markError(errStart, startInput, 'Эхлэх огноо, цаг оруулна уу.');
      }

      if (!endDt) {
        markError(errEnd, endInput, 'Дуусах огноо, цаг оруулна уу.');
      } else if (startDt && new Date(endDt) <= new Date(startDt)) {
        markError(errEnd, endInput, 'Дуусах огноо эхлэх огнооноос хойш байх ёстой.');
      }

      if (!guests || parseInt(guests, 10) < 1) {
        markError(errGuests, guestInput, 'Хүний тоо оруулна уу.');
      } else {
        var guestsNum = parseInt(guests, 10);
        var campCap = CAMP_CAPACITY[camp];
        if (campCap) {
          if (guestsNum < campCap.min) {
            markError(errGuests, guestInput, 'Энэ кемпийн хамгийн бага хүний тоо ' + campCap.min + ' байна.');
          } else if (guestsNum > campCap.max) {
            markError(errGuests, guestInput, 'Энэ кемпийн хамгийн их хүний тоо ' + campCap.max + ' байна.');
          }
        }
      }

      if (isMobile && !location) {
        markError(errLocation, locationInput, 'Кемп байгуулах байршил оруулна уу.');
      }

      if (hasError) {
        if (firstErrorEl) firstErrorEl.focus();
        return;
      }

      var submitBtn = quoteForm.querySelector('[type="submit"]');
      if (submitBtn) { submitBtn.disabled = true; submitBtn.textContent = 'Илгээж байна…'; }

      var guestsInt = parseInt(guests, 10) || 0;
      var selectedAddons = [];
      quoteForm.querySelectorAll('input[name="addons[]"]:checked').forEach(function (cb) {
        var card = cb.closest('.quote-addon-card');
        var item = {
          code:          cb.value,
          name:          cb.dataset.label || cb.value,
          type:          cb.dataset.type  || 'unknown',
          tier_included: cb.disabled
        };
        if (cb.dataset.type === 'per-person' && !cb.disabled) {
          var qtyInput = card ? card.querySelector('.quote-addon-card__qty-input') : null;
          item.quantity   = qtyInput ? (parseInt(qtyInput.value, 10) || guestsInt) : guestsInt;
          item.unit_price = parseInt(cb.dataset.price, 10) || 0;
          item.price      = item.unit_price * item.quantity;
        } else if (cb.value === 'dj_service' && !cb.disabled) {
          var djS = parseInt((document.querySelector('[name="dj_start_time"]') || {}).value, 10) || 18;
          var djE = parseInt((document.querySelector('[name="dj_end_time"]')   || {}).value, 10) || 20;
          item.start_time = djS + ':00';
          item.end_time   = djE <= 24 ? djE + ':00' : (djE - 24) + ':00';
          item.duration   = djE - djS;
          item.price      = calculateDJPrice();
        } else if (cb.value === 'bartender_service' && !cb.disabled) {
          item.bartender_count = Math.ceil(guestsInt / 75) || 1;
          item.price           = calculateBartenderPrice(guestsInt);
        } else if (cb.value === 'medical_service' && !cb.disabled) {
          item.medical_count = Math.ceil(guestsInt / 500) || 1;
          item.price         = calculateMedicalPrice(guestsInt);
        } else if (cb.value === 'security_service' && !cb.disabled) {
          item.officer_count = Math.max(2, Math.ceil(guestsInt / 100));
          item.price         = calculateSecurityPrice(guestsInt);
        } else if (cb.dataset.price && !cb.disabled) {
          item.price = parseInt(cb.dataset.price, 10);
        }
        if (cb.value === 'welcome_drink' && !cb.disabled) {
          var drinkTypeEl = quoteForm.querySelector('input[name="welcome_drink_type"]:checked');
          if (drinkTypeEl) item.drink_type = drinkTypeEl.value;
        }
        selectedAddons.push(item);
      });

      var addonEstimatedTotal = 0;
      selectedAddons.forEach(function (a) {
        if (!a.tier_included && a.price) addonEstimatedTotal += a.price;
      });

      var payload = {
        camp:                  camp,
        tier:                  tier,
        visual_feature:        (fd.get('visual_feature')  || '').trim(),
        shuttle_service:       (fd.get('shuttle_service') || '').trim(),
        bus_count:             (fd.get('bus_count') ? parseInt(fd.get('bus_count'), 10) : 1),
        location:              isMobile ? location : '',
        notes:                 (fd.get('extra_info')      || '').trim(),
        company:               org,
        contact_name:          contact,
        phone:                 phone,
        email:                 email,
        start_datetime:        startDt,
        end_datetime:          endDt,
        event_date:            startDt,
        guest_count:           guests,
        camp_name:             camp,
        package_tier:          tier,
        shuttle_service_label: (fd.get('shuttle_service') || '').trim(),
        addons_json:           JSON.stringify(selectedAddons),
        addon_count:           selectedAddons.length,
        estimated_addon_total: addonEstimatedTotal,
        source:                'nomaadcamp.com'
      };

      try {
        var res = await fetch(N8N_WEBHOOK_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        });
        if (!res.ok) throw new Error('HTTP ' + res.status);
        if (quoteMessage) {
          quoteMessage.textContent = 'Таны хүсэлт амжилттай илгээгдлээ. Манай баг 24 цагийн дотор холбогдоно.';
          quoteMessage.className = 'quote-form__message quote-form__message--success';
        }
        quoteForm.reset();
        applyLocationVisibility('');
        window.setTimeout(function () { closeQuoteModal(); }, 3000);
      } catch (_) {
        if (quoteMessage) {
          quoteMessage.textContent = 'Алдаа гарлаа. Дахин оролдох эсвэл 9917-9417 дугаарт залгана уу.';
          quoteMessage.className = 'quote-form__message quote-form__message--error';
        }
      } finally {
        if (submitBtn) { submitBtn.disabled = false; submitBtn.textContent = 'Урьдчилсан санал авах'; }
      }
    });
  }

  // Package card accordions — wire up aria-controls/id pairs and click handlers
  document.querySelectorAll('.pkg-accordion__toggle').forEach(function (btn, idx) {
    var accordion = btn.closest('.pkg-accordion');
    var body = accordion ? accordion.querySelector('.pkg-accordion__body') : null;
    if (body && !body.id) body.id = 'accordion-body-' + idx;
    if (body) btn.setAttribute('aria-controls', body.id);
    btn.addEventListener('click', function () {
      var isOpen = accordion.classList.contains('is-open');
      accordion.classList.toggle('is-open', !isOpen);
      btn.setAttribute('aria-expanded', String(!isOpen));
    });
  });

  // Camp card buttons — wire up aria-controls to the camp detail sections
  document.querySelectorAll('.camp-card[data-camp-target]').forEach(function (btn) {
    btn.setAttribute('aria-controls', btn.dataset.campTarget);
  });
})();
