// NOMAAD Image Manifest — auto-generated by scripts/generate-manifest.js
// DO NOT edit by hand. To add images:
//   cover image  → images/camps/<camp>/cover/<any-filename>
//   gallery image → images/camps/<camp>/gallery/<any-filename>
//   partner logos → logos/partners/<any-filename>
// Then commit and push — Netlify regenerates this file on every deploy.
window.NOMAAD_IMAGES = {
  "hero": [
    "/images/hero/gallery-05.jpg",
    "/images/hero/gallery-17.jpg",
    "/images/hero/gallery-18.jpg",
    "/images/hero/gallery-19.jpg",
    "/images/hero/hero-01.jpg"
  ],
  "gallery": [
    "/images/gallery/gallery-09.jpg",
    "/images/gallery/gallery-10.jpg",
    "/images/gallery/gallery-20.jpg"
  ],
  "partners": [
    "/logos/partners/client-apu.svg",
    "/logos/partners/client-golomt.svg",
    "/logos/partners/client-khan.svg",
    "/logos/partners/client-mcs.svg",
    "/logos/partners/client-tt.svg",
    "/logos/partners/client-unitel.svg"
  ],
  "galleryCategories": {
    "stage": {
      "title": "Тайз ба хөтөлбөр",
      "label": "STAGE",
      "description": "Том хэмжээний outdoor арга хэмжээний тайз болон хөтөлбөрийн орчин.",
      "cover": null,
      "images": []
    },
    "lounge": {
      "title": "Чөлөөт орчин",
      "label": "Чөлөөт орчин",
      "description": "Чөлөөт харилцаа, амралт болон outdoor acoustic орчны зохион байгуулалт.",
      "cover": "/images/gallery/lounge/01.jpg",
      "images": [
        "/images/gallery/lounge/01.jpg"
      ]
    },
    "dining": {
      "title": "Катеринг үйлчилгээ",
      "label": "Катеринг",
      "description": "Байгууллагын арга хэмжээнд зориулсан катеринг болон buffet үйлчилгээг нэгдсэн байдлаар зохион байгуулна.",
      "cover": "/images/gallery/dining/477734850_1136988128222589_3475023461521596684_n.jpg",
      "images": [
        "/images/gallery/dining/477734850_1136988128222589_3475023461521596684_n.jpg",
        "/images/gallery/dining/481080072_1152247096696692_1157408756925740180_n.jpg",
        "/images/gallery/dining/481084542_1150137226907679_7302794082867681262_n.jpg",
        "/images/gallery/dining/481119357_1151578200096915_2968307237344432604_n.jpg",
        "/images/gallery/dining/481270158_1150900113498057_385902645609428743_n.jpg",
        "/images/gallery/dining/481897943_1151578180096917_3016324357198583754_n.jpg"
      ]
    },
    "setup": {
      "title": "Setup ба бэлтгэл",
      "label": "SETUP",
      "description": "Тохижилт, техник, дэд бүтэц — арга хэмжээний өдрийн өмнөх бэлтгэл.",
      "cover": "/images/gallery/setup/481023225_1152247153363353_5018493050852888482_n.jpg",
      "images": [
        "/images/gallery/setup/481023225_1152247153363353_5018493050852888482_n.jpg",
        "/images/gallery/setup/481084746_1150900190164716_2002492711595995957_n.jpg",
        "/images/gallery/setup/481216510_1150900090164726_6144427359539858322_n.jpg",
        "/images/gallery/setup/481475628_1150900080164727_3243613269616035992_n.jpg",
        "/images/gallery/setup/481475920_1150900060164729_8102678781114645058_n.jpg",
        "/images/gallery/setup/IMG_0499.JPG",
        "/images/gallery/setup/Screenshot 2026-04-26 at 19.01.01.png",
        "/images/gallery/setup/gallery-20.jpg"
      ]
    },
    "team": {
      "title": "Баг ба оролцогчид",
      "label": "TEAM",
      "description": "NOMAAD баг болон оролцогчдын хамтын ажиллагаа, тэмцэл, баяр.",
      "cover": null,
      "images": []
    },
    "night": {
      "title": "Оройн хөтөлбөр",
      "label": "NIGHT",
      "description": "Орой болсон хойно — гэрэлтүүлэг, DJ, Bartender, шөнийн уур амьсгал.",
      "cover": null,
      "images": []
    }
  },
  "camps": {
    "a": {
      "cover": "/images/camps/a-camp/cover/516791132_1249324066988994_7236995618864252267_n.jpg",
      "gallery": [
        "/images/camps/a-camp/gallery/481079165_1152247143363354_6339986456406502712_n.jpg",
        "/images/camps/a-camp/gallery/481216510_1150900090164726_6144427359539858322_n.jpg",
        "/images/camps/a-camp/gallery/481261911_1151578586763543_4790611935648483867_n.jpg",
        "/images/camps/a-camp/gallery/481290304_1150899923498076_146070325897299227_n.jpg",
        "/images/camps/a-camp/gallery/481475628_1150900080164727_3243613269616035992_n.jpg",
        "/images/camps/a-camp/gallery/481475920_1150900060164729_8102678781114645058_n.jpg",
        "/images/camps/a-camp/gallery/481677024_1152247130030022_4616486509329515100_n.jpg",
        "/images/camps/a-camp/gallery/482049701_1152238963364172_4623094402279520580_n.jpg",
        "/images/camps/a-camp/gallery/498673752_1211111604143574_1980107969661774275_n.jpg",
        "/images/camps/a-camp/gallery/508577864_1234422215145846_5726433488358768002_n.jpg",
        "/images/camps/a-camp/gallery/526782782_1269315874989813_7037524833627375972_n.jpg",
        "/images/camps/a-camp/gallery/Screenshot 2026-04-26 at 12.27.10.png"
      ]
    },
    "b": {
      "cover": "/images/camps/b-camp/cover/DJI_20250725152844_0015_D.jpg",
      "gallery": [
        "/images/camps/b-camp/gallery/525225068_1267547411833326_6748176839399281706_n.jpg",
        "/images/camps/b-camp/gallery/DJI_20250725152831_0014_D.jpg",
        "/images/camps/b-camp/gallery/b2.jpg",
        "/images/camps/b-camp/gallery/b3.jpg",
        "/images/camps/b-camp/gallery/b4.jpg",
        "/images/camps/b-camp/gallery/bcamp.jpg",
        "/images/camps/b-camp/gallery/gallery-07.jpg"
      ]
    },
    "c": {
      "cover": "/images/camps/c-camp/cover/c-cover.jpg",
      "gallery": [
        "/images/camps/c-camp/gallery/2.webp",
        "/images/camps/c-camp/gallery/c2.jpg",
        "/images/camps/c-camp/gallery/c4.jpg"
      ]
    },
    "mobile": {
      "cover": "/images/camps/mobile-camp/cover/gallery-20.jpg",
      "gallery": [
        "/images/camps/mobile-camp/gallery/480926596_1150142873573781_120003575192392008_n.jpg",
        "/images/camps/mobile-camp/gallery/481002059_1152069033381165_4247459599491477283_n.jpg",
        "/images/camps/mobile-camp/gallery/481153087_1150142846907117_5843438727625385537_n.jpg",
        "/images/camps/mobile-camp/gallery/481914247_1152616986659703_5992810539030354001_n.jpg",
        "/images/camps/mobile-camp/gallery/496846586_1205121231409278_6731493953383684426_n.jpg",
        "/images/camps/mobile-camp/gallery/DSC07839.jpg"
      ]
    }
  }
};
